### ISSUE TITLE
Missing dependency babel-core in package.json

### ISSUE THREAD

**Issue by thepont** [bigdatr/elephas#10]
Elephas requires `babel-core` but does not have it in it's package.json

The following error is thrown if a package using elephas does not also require babel.

```
2016-05-24T05:41:21.489Z - error: caught exception : s Error: Cannot find module 'babel-core/register'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/paulesson/projects/trc-contractor-auth/node_modules/elephas/elephas.js:1:63)
    at Module._compile (module.js:409:26)
    at Module._extensions..js (module.js:416:10)
    at Object.require.extensions.(anonymous function) [as .js] (/home/paulesson/projects/trc-contractor-auth/node_modules/babel-register/lib/node.js:166:7)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at init (app.js:55:23)
    at process._tickCallback (node.js:369:9)

```

**Comment by atridgedcosta** [comment]
This is a webpack thing. Elephas doesn't need it but your app needs to use babel-core and then make sure it includes elephas. Check with @allanhortle
